name: 'test' 
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Create pull request
        id: create-pull-request
      - name: Print the branches
        run : |
          echo ${{steps.create-pull-request.outputs.from-branch}}
          echo ${{steps.create-pull-request.outputs.to-branch}}
